### ISSUE TITLE
Prevent Buying assets below an specific MANA value using meta-tx

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/dapps-issues#23]
To do:

- [x] feat: Add price check to transaction server: https://github.com/decentraland/transactions-server/issues/80
- [x] feat: Handle sale price error on decentraland-transactions: https://github.com/decentraland/decentraland-transactions/issues/43
- [x] feat: show a modal for the new sale price error code: https://github.com/decentraland/decentraland-dapps/issues/226
- [x] chore: Reuse mapping function: https://github.com/decentraland/common-schemas/issues/68
- [x] fix: add biconomy error codes again decentraland/transactions-server#82

Unhide zero priced items:
- [x] feat: return " invalid "  sale prices from nft server: https://github.com/decentraland/nft-server/issues/49
- [x] feat: revert hiding 0-priced items: https://github.com/decentraland/marketplace/issues/616
